### ISSUE TITLE
Changing original image dynamically

### ISSUE THREAD

**Issue by jamiemcl** [bcabanes/angular-image-cropper#3] opened 2015-09-16 21:43 UTC
Hello,

I'd just like to say thanks for the plugin - it really has helped me as I was struggling to find anything that was suitable for cropping on a mobile device and almost got ready to develop something like this myself. You've saved me a lot of time!

I have one question though (and I'm not sure it's an issue) - when I change the original image dynamically to an image which is smaller in size, some of the cropped image result is cut off and displayed as blank. I'm guessing that I need to somehow refresh the directive once the image has been changed. Is there an easy way to achieve this?

![crop](https://cloud.githubusercontent.com/assets/4104129/9919410/8dafe71e-5cc4-11e5-8a42-86964e776783.png)

**Comment by bcabanes** [comment] 2015-09-19 18:29
Hi @jamiemcl and thank you!
Unfortunately, i can't reproduce what you're explaining so could you create a [plunkr](http://plnkr.co/) or [jsbin](https://jsbin.com) to show me your problem?
Normally, if you change the image, the directive should reload itself with the new image.

++

**Comment by andreafdaf** [comment] 2015-10-16 01:06
I'm having a similar problem but when using big images, it never happens at the first try (even if the image is 10MB), but if you load big, small, big, small, a couple of times it always happens...

![1](https://cloud.githubusercontent.com/assets/11524895/10531448/1adfde60-73b2-11e5-8336-a00e6a3ce082.png)

![2](https://cloud.githubusercontent.com/assets/11524895/10531450/235d3858-73b2-11e5-8c4e-e6facb3c3b46.png)

![3](https://cloud.githubusercontent.com/assets/11524895/10531472/78afc456-73b2-11e5-890c-8465ef7019ab.png)

the above images were loaded in order, the first one is big, the second one is big (and there you see the problem), the third one is small so things go back to normal but after it happens the first time the directive never works fine again with images bigger than 520-550kB, if you load a small image it works fine but if the image is heavier than this threshold it gets zoomed way out, a big part of the image gets ignored (so most of the cropped image is black) and the center of this strangely cropped image gets pushed a lot towards up and left

**Comment by bcabanes** [comment] 2016-02-19 16:36
A new version is available. Closing.

**Closed by bcabanes** 2016-02-19 16:36 UTC
